###Home page
GET http://localhost:8085

###Fetching Access Token
GET http://localhost:8085/api/getAccessToken/eu

###Playable Races Index
GET https://us.api.blizzard.com/data/wow/playable-race/index?namespace=static-classic-us&locale=en_US&access_token=EUW5nbYYRvi27pVlj2KksCC7OmKbR9DvVX

###Playable Race
GET https://us.api.blizzard.com/data/wow/playable-race/2?namespace=static-classic-us&locale=en_US&access_token=EUW5nbYYRvi27pVlj2KksCC7OmKbR9DvVX

###Playable Classes Index
GET https://us.api.blizzard.com/data/wow/playable-class/index?namespace=static-classic-us&locale=en_US&access_token=EUW5nbYYRvi27pVlj2KksCC7OmKbR9DvVX

###Playable Class
GET https://us.api.blizzard.com/data/wow/playable-class/7?namespace=static-classic-us&locale=en_US&access_token=EUW5nbYYRvi27pVlj2KksCC7OmKbR9DvVX

###Playable Class Media
GET https://us.api.blizzard.com/data/wow/media/playable-class/7?namespace=static-classic-us&locale=en_US&access_token=EUW5nbYYRvi27pVlj2KksCC7OmKbR9DvVX